[package]
name = "filters"
version = "0.1.0"
edition = "2024"

[dependencies]
num-traits = "0.2.19"
vector_quaternion_matrix = { git = "https://github.com/martinbudden/Crate-vector_quaternion_matrix" }
